// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: synq/ingest/dbt/v1/dbt_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DbtService_IngestInvocation_FullMethodName = "/synq.ingest.dbt.v1.DbtService/IngestInvocation"
)

// DbtServiceClient is the client API for DbtService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DbtServiceClient interface {
	IngestInvocation(ctx context.Context, in *IngestInvocationRequest, opts ...grpc.CallOption) (*IngestInvocationResponse, error)
}

type dbtServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDbtServiceClient(cc grpc.ClientConnInterface) DbtServiceClient {
	return &dbtServiceClient{cc}
}

func (c *dbtServiceClient) IngestInvocation(ctx context.Context, in *IngestInvocationRequest, opts ...grpc.CallOption) (*IngestInvocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestInvocationResponse)
	err := c.cc.Invoke(ctx, DbtService_IngestInvocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DbtServiceServer is the server API for DbtService service.
// All implementations must embed UnimplementedDbtServiceServer
// for forward compatibility.
type DbtServiceServer interface {
	IngestInvocation(context.Context, *IngestInvocationRequest) (*IngestInvocationResponse, error)
	mustEmbedUnimplementedDbtServiceServer()
}

// UnimplementedDbtServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDbtServiceServer struct{}

func (UnimplementedDbtServiceServer) IngestInvocation(context.Context, *IngestInvocationRequest) (*IngestInvocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngestInvocation not implemented")
}
func (UnimplementedDbtServiceServer) mustEmbedUnimplementedDbtServiceServer() {}
func (UnimplementedDbtServiceServer) testEmbeddedByValue()                    {}

// UnsafeDbtServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DbtServiceServer will
// result in compilation errors.
type UnsafeDbtServiceServer interface {
	mustEmbedUnimplementedDbtServiceServer()
}

func RegisterDbtServiceServer(s grpc.ServiceRegistrar, srv DbtServiceServer) {
	// If the following call pancis, it indicates UnimplementedDbtServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DbtService_ServiceDesc, srv)
}

func _DbtService_IngestInvocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestInvocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbtServiceServer).IngestInvocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbtService_IngestInvocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbtServiceServer).IngestInvocation(ctx, req.(*IngestInvocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DbtService_ServiceDesc is the grpc.ServiceDesc for DbtService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DbtService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "synq.ingest.dbt.v1.DbtService",
	HandlerType: (*DbtServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngestInvocation",
			Handler:    _DbtService_IngestInvocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "synq/ingest/dbt/v1/dbt_service.proto",
}
