// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: synq/entities/entities/v1/entities_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EntitiesService_GetEntity_FullMethodName        = "/synq.entities.entities.v1.EntitiesService/GetEntity"
	EntitiesService_BatchGetEntities_FullMethodName = "/synq.entities.entities.v1.EntitiesService/BatchGetEntities"
)

// EntitiesServiceClient is the client API for EntitiesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EntitiesService is a service for retriving any entity.
type EntitiesServiceClient interface {
	// Get specific entity by its identifier.
	GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error)
	// Get multiple entities by their identifiers.
	BatchGetEntities(ctx context.Context, in *BatchGetEntitiesRequest, opts ...grpc.CallOption) (*BatchGetEntitiesResponse, error)
}

type entitiesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEntitiesServiceClient(cc grpc.ClientConnInterface) EntitiesServiceClient {
	return &entitiesServiceClient{cc}
}

func (c *entitiesServiceClient) GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntityResponse)
	err := c.cc.Invoke(ctx, EntitiesService_GetEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entitiesServiceClient) BatchGetEntities(ctx context.Context, in *BatchGetEntitiesRequest, opts ...grpc.CallOption) (*BatchGetEntitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetEntitiesResponse)
	err := c.cc.Invoke(ctx, EntitiesService_BatchGetEntities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntitiesServiceServer is the server API for EntitiesService service.
// All implementations must embed UnimplementedEntitiesServiceServer
// for forward compatibility.
//
// EntitiesService is a service for retriving any entity.
type EntitiesServiceServer interface {
	// Get specific entity by its identifier.
	GetEntity(context.Context, *GetEntityRequest) (*GetEntityResponse, error)
	// Get multiple entities by their identifiers.
	BatchGetEntities(context.Context, *BatchGetEntitiesRequest) (*BatchGetEntitiesResponse, error)
	mustEmbedUnimplementedEntitiesServiceServer()
}

// UnimplementedEntitiesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEntitiesServiceServer struct{}

func (UnimplementedEntitiesServiceServer) GetEntity(context.Context, *GetEntityRequest) (*GetEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntity not implemented")
}
func (UnimplementedEntitiesServiceServer) BatchGetEntities(context.Context, *BatchGetEntitiesRequest) (*BatchGetEntitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetEntities not implemented")
}
func (UnimplementedEntitiesServiceServer) mustEmbedUnimplementedEntitiesServiceServer() {}
func (UnimplementedEntitiesServiceServer) testEmbeddedByValue()                         {}

// UnsafeEntitiesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EntitiesServiceServer will
// result in compilation errors.
type UnsafeEntitiesServiceServer interface {
	mustEmbedUnimplementedEntitiesServiceServer()
}

func RegisterEntitiesServiceServer(s grpc.ServiceRegistrar, srv EntitiesServiceServer) {
	// If the following call pancis, it indicates UnimplementedEntitiesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EntitiesService_ServiceDesc, srv)
}

func _EntitiesService_GetEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitiesServiceServer).GetEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntitiesService_GetEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitiesServiceServer).GetEntity(ctx, req.(*GetEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntitiesService_BatchGetEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetEntitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitiesServiceServer).BatchGetEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntitiesService_BatchGetEntities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitiesServiceServer).BatchGetEntities(ctx, req.(*BatchGetEntitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EntitiesService_ServiceDesc is the grpc.ServiceDesc for EntitiesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EntitiesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "synq.entities.entities.v1.EntitiesService",
	HandlerType: (*EntitiesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEntity",
			Handler:    _EntitiesService_GetEntity_Handler,
		},
		{
			MethodName: "BatchGetEntities",
			Handler:    _EntitiesService_BatchGetEntities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "synq/entities/entities/v1/entities_service.proto",
}
