// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: synq/agent/dwh/v1/dwh_agent_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DwhAgentService_Connect_FullMethodName = "/synq.agent.dwh.v1.DwhAgentService/Connect"
)

// DwhAgentServiceClient is the client API for DwhAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DwhAgentServiceClient interface {
	// buf:lint:ignore RPC_NO_CLIENT_STREAMING
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnectRequest, ConnectResponse], error)
}

type dwhAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDwhAgentServiceClient(cc grpc.ClientConnInterface) DwhAgentServiceClient {
	return &dwhAgentServiceClient{cc}
}

func (c *dwhAgentServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnectRequest, ConnectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DwhAgentService_ServiceDesc.Streams[0], DwhAgentService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConnectRequest, ConnectResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DwhAgentService_ConnectClient = grpc.BidiStreamingClient[ConnectRequest, ConnectResponse]

// DwhAgentServiceServer is the server API for DwhAgentService service.
// All implementations must embed UnimplementedDwhAgentServiceServer
// for forward compatibility.
type DwhAgentServiceServer interface {
	// buf:lint:ignore RPC_NO_CLIENT_STREAMING
	Connect(grpc.BidiStreamingServer[ConnectRequest, ConnectResponse]) error
	mustEmbedUnimplementedDwhAgentServiceServer()
}

// UnimplementedDwhAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDwhAgentServiceServer struct{}

func (UnimplementedDwhAgentServiceServer) Connect(grpc.BidiStreamingServer[ConnectRequest, ConnectResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedDwhAgentServiceServer) mustEmbedUnimplementedDwhAgentServiceServer() {}
func (UnimplementedDwhAgentServiceServer) testEmbeddedByValue()                         {}

// UnsafeDwhAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DwhAgentServiceServer will
// result in compilation errors.
type UnsafeDwhAgentServiceServer interface {
	mustEmbedUnimplementedDwhAgentServiceServer()
}

func RegisterDwhAgentServiceServer(s grpc.ServiceRegistrar, srv DwhAgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedDwhAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DwhAgentService_ServiceDesc, srv)
}

func _DwhAgentService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DwhAgentServiceServer).Connect(&grpc.GenericServerStream[ConnectRequest, ConnectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DwhAgentService_ConnectServer = grpc.BidiStreamingServer[ConnectRequest, ConnectResponse]

// DwhAgentService_ServiceDesc is the grpc.ServiceDesc for DwhAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DwhAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "synq.agent.dwh.v1.DwhAgentService",
	HandlerType: (*DwhAgentServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _DwhAgentService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "synq/agent/dwh/v1/dwh_agent_service.proto",
}
