// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: synq/entities/lineage/v1/lineage_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LineageService_GetLineage_FullMethodName = "/synq.entities.lineage.v1.LineageService/GetLineage"
)

// LineageServiceClient is the client API for LineageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LineageService allows you to fetch:
// * Entity level lineage from a starting point of one or more entities.
// * Column Level lineage from a starting point of multiple columns of a single entity.
type LineageServiceClient interface {
	GetLineage(ctx context.Context, in *GetLineageRequest, opts ...grpc.CallOption) (*GetLineageResponse, error)
}

type lineageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLineageServiceClient(cc grpc.ClientConnInterface) LineageServiceClient {
	return &lineageServiceClient{cc}
}

func (c *lineageServiceClient) GetLineage(ctx context.Context, in *GetLineageRequest, opts ...grpc.CallOption) (*GetLineageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLineageResponse)
	err := c.cc.Invoke(ctx, LineageService_GetLineage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LineageServiceServer is the server API for LineageService service.
// All implementations must embed UnimplementedLineageServiceServer
// for forward compatibility.
//
// LineageService allows you to fetch:
// * Entity level lineage from a starting point of one or more entities.
// * Column Level lineage from a starting point of multiple columns of a single entity.
type LineageServiceServer interface {
	GetLineage(context.Context, *GetLineageRequest) (*GetLineageResponse, error)
	mustEmbedUnimplementedLineageServiceServer()
}

// UnimplementedLineageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLineageServiceServer struct{}

func (UnimplementedLineageServiceServer) GetLineage(context.Context, *GetLineageRequest) (*GetLineageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLineage not implemented")
}
func (UnimplementedLineageServiceServer) mustEmbedUnimplementedLineageServiceServer() {}
func (UnimplementedLineageServiceServer) testEmbeddedByValue()                        {}

// UnsafeLineageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LineageServiceServer will
// result in compilation errors.
type UnsafeLineageServiceServer interface {
	mustEmbedUnimplementedLineageServiceServer()
}

func RegisterLineageServiceServer(s grpc.ServiceRegistrar, srv LineageServiceServer) {
	// If the following call pancis, it indicates UnimplementedLineageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LineageService_ServiceDesc, srv)
}

func _LineageService_GetLineage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLineageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LineageServiceServer).GetLineage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LineageService_GetLineage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LineageServiceServer).GetLineage(ctx, req.(*GetLineageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LineageService_ServiceDesc is the grpc.ServiceDesc for LineageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LineageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "synq.entities.lineage.v1.LineageService",
	HandlerType: (*LineageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLineage",
			Handler:    _LineageService_GetLineage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "synq/entities/lineage/v1/lineage_service.proto",
}
