// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        (unknown)
// source: synq/queries/v1/query_parts.proto

package v1

import (
	v1 "github.com/getsynq/api/entities/v1"
	v11 "github.com/getsynq/api/platforms/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Resolves to entities matching any of the given identifiers.
type IdentifierList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifiers   []*v1.Identifier       `protobuf:"bytes,1,rep,name=identifiers,proto3" json:"identifiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentifierList) Reset() {
	*x = IdentifierList{}
	mi := &file_synq_queries_v1_query_parts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifierList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifierList) ProtoMessage() {}

func (x *IdentifierList) ProtoReflect() protoreflect.Message {
	mi := &file_synq_queries_v1_query_parts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifierList.ProtoReflect.Descriptor instead.
func (*IdentifierList) Descriptor() ([]byte, []int) {
	return file_synq_queries_v1_query_parts_proto_rawDescGZIP(), []int{0}
}

func (x *IdentifierList) GetIdentifiers() []*v1.Identifier {
	if x != nil {
		return x.Identifiers
	}
	return nil
}

// Resolves to all entities matching the given name search.
type WithNameSearch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchQuery   string                 `protobuf:"bytes,1,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithNameSearch) Reset() {
	*x = WithNameSearch{}
	mi := &file_synq_queries_v1_query_parts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithNameSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithNameSearch) ProtoMessage() {}

func (x *WithNameSearch) ProtoReflect() protoreflect.Message {
	mi := &file_synq_queries_v1_query_parts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithNameSearch.ProtoReflect.Descriptor instead.
func (*WithNameSearch) Descriptor() ([]byte, []int) {
	return file_synq_queries_v1_query_parts_proto_rawDescGZIP(), []int{1}
}

func (x *WithNameSearch) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

// Resolves to all the entities that have the provided type.
type WithType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *WithType_Type         `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithType) Reset() {
	*x = WithType{}
	mi := &file_synq_queries_v1_query_parts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithType) ProtoMessage() {}

func (x *WithType) ProtoReflect() protoreflect.Message {
	mi := &file_synq_queries_v1_query_parts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithType.ProtoReflect.Descriptor instead.
func (*WithType) Descriptor() ([]byte, []int) {
	return file_synq_queries_v1_query_parts_proto_rawDescGZIP(), []int{2}
}

func (x *WithType) GetType() *WithType_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

// Resolves to all entities that contain the annotation with the provided accepted value.
// In case of no given accepted value, all entities that carry the given annotation are returned.
type WithAnnotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AcceptedValue *string                `protobuf:"bytes,2,opt,name=accepted_value,json=acceptedValue,proto3,oneof" json:"accepted_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithAnnotation) Reset() {
	*x = WithAnnotation{}
	mi := &file_synq_queries_v1_query_parts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithAnnotation) ProtoMessage() {}

func (x *WithAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_synq_queries_v1_query_parts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithAnnotation.ProtoReflect.Descriptor instead.
func (*WithAnnotation) Descriptor() ([]byte, []int) {
	return file_synq_queries_v1_query_parts_proto_rawDescGZIP(), []int{3}
}

func (x *WithAnnotation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WithAnnotation) GetAcceptedValue() string {
	if x != nil && x.AcceptedValue != nil {
		return *x.AcceptedValue
	}
	return ""
}

// Resolves to all the assets that belong to the given data product.
type InDataproduct struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Identifier    *v1.DataproductIdentifier `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InDataproduct) Reset() {
	*x = InDataproduct{}
	mi := &file_synq_queries_v1_query_parts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InDataproduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InDataproduct) ProtoMessage() {}

func (x *InDataproduct) ProtoReflect() protoreflect.Message {
	mi := &file_synq_queries_v1_query_parts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InDataproduct.ProtoReflect.Descriptor instead.
func (*InDataproduct) Descriptor() ([]byte, []int) {
	return file_synq_queries_v1_query_parts_proto_rawDescGZIP(), []int{4}
}

func (x *InDataproduct) GetIdentifier() *v1.DataproductIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

// Resolves to all entities that belong to the given data platform.
type InDataPlatform struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Identifier    *v11.DataPlatformIdentifier `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InDataPlatform) Reset() {
	*x = InDataPlatform{}
	mi := &file_synq_queries_v1_query_parts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InDataPlatform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InDataPlatform) ProtoMessage() {}

func (x *InDataPlatform) ProtoReflect() protoreflect.Message {
	mi := &file_synq_queries_v1_query_parts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InDataPlatform.ProtoReflect.Descriptor instead.
func (*InDataPlatform) Descriptor() ([]byte, []int) {
	return file_synq_queries_v1_query_parts_proto_rawDescGZIP(), []int{5}
}

func (x *InDataPlatform) GetIdentifier() *v11.DataPlatformIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

// Resolves to all entities belonging to the given folder structure.
type InFolder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []string               `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InFolder) Reset() {
	*x = InFolder{}
	mi := &file_synq_queries_v1_query_parts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InFolder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InFolder) ProtoMessage() {}

func (x *InFolder) ProtoReflect() protoreflect.Message {
	mi := &file_synq_queries_v1_query_parts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InFolder.ProtoReflect.Descriptor instead.
func (*InFolder) Descriptor() ([]byte, []int) {
	return file_synq_queries_v1_query_parts_proto_rawDescGZIP(), []int{6}
}

func (x *InFolder) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

// Collects all the parts of the query that are currently unsupported in translation.
// These represent an internal structure that are not yet completely available on the API.
type Unsupported struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryJson     string                 `protobuf:"bytes,1,opt,name=query_json,json=queryJson,proto3" json:"query_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unsupported) Reset() {
	*x = Unsupported{}
	mi := &file_synq_queries_v1_query_parts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unsupported) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unsupported) ProtoMessage() {}

func (x *Unsupported) ProtoReflect() protoreflect.Message {
	mi := &file_synq_queries_v1_query_parts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unsupported.ProtoReflect.Descriptor instead.
func (*Unsupported) Descriptor() ([]byte, []int) {
	return file_synq_queries_v1_query_parts_proto_rawDescGZIP(), []int{7}
}

func (x *Unsupported) GetQueryJson() string {
	if x != nil {
		return x.QueryJson
	}
	return ""
}

type WithType_Type struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to EntityType:
	//
	//	*WithType_Type_Default
	//	*WithType_Type_Custom
	EntityType    isWithType_Type_EntityType `protobuf_oneof:"entity_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithType_Type) Reset() {
	*x = WithType_Type{}
	mi := &file_synq_queries_v1_query_parts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithType_Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithType_Type) ProtoMessage() {}

func (x *WithType_Type) ProtoReflect() protoreflect.Message {
	mi := &file_synq_queries_v1_query_parts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithType_Type.ProtoReflect.Descriptor instead.
func (*WithType_Type) Descriptor() ([]byte, []int) {
	return file_synq_queries_v1_query_parts_proto_rawDescGZIP(), []int{2, 0}
}

func (x *WithType_Type) GetEntityType() isWithType_Type_EntityType {
	if x != nil {
		return x.EntityType
	}
	return nil
}

func (x *WithType_Type) GetDefault() v1.EntityType {
	if x != nil {
		if x, ok := x.EntityType.(*WithType_Type_Default); ok {
			return x.Default
		}
	}
	return v1.EntityType(0)
}

func (x *WithType_Type) GetCustom() int32 {
	if x != nil {
		if x, ok := x.EntityType.(*WithType_Type_Custom); ok {
			return x.Custom
		}
	}
	return 0
}

type isWithType_Type_EntityType interface {
	isWithType_Type_EntityType()
}

type WithType_Type_Default struct {
	// Default SYNQ types
	Default v1.EntityType `protobuf:"varint,1,opt,name=default,proto3,enum=synq.entities.v1.EntityType,oneof"`
}

type WithType_Type_Custom struct {
	// Custom types as defined through synq.entities.custom.v1.TypesService
	Custom int32 `protobuf:"varint,2,opt,name=custom,proto3,oneof"`
}

func (*WithType_Type_Default) isWithType_Type_EntityType() {}

func (*WithType_Type_Custom) isWithType_Type_EntityType() {}

var File_synq_queries_v1_query_parts_proto protoreflect.FileDescriptor

var file_synq_queries_v1_query_parts_proto_rawDesc = string([]byte{
	0x0a, 0x21, 0x73, 0x79, 0x6e, 0x71, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x76,
	0x31, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x73, 0x79, 0x6e, 0x71, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65,
	0x73, 0x2e, 0x76, 0x31, 0x1a, 0x23, 0x73, 0x79, 0x6e, 0x71, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x73, 0x79, 0x6e, 0x71, 0x2f,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x26, 0x73, 0x79,
	0x6e, 0x71, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x2f, 0x76, 0x31, 0x2f,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x0e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x0b, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x79,
	0x6e, 0x71, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x0b, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x22, 0x33, 0x0a, 0x0e, 0x57, 0x69, 0x74, 0x68, 0x4e, 0x61,
	0x6d, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x51, 0x75, 0x65, 0x72, 0x79, 0x22, 0xa9, 0x01, 0x0a, 0x08,
	0x57, 0x69, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x79, 0x6e, 0x71, 0x2e, 0x71, 0x75,
	0x65, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x54, 0x79, 0x70,
	0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x1a, 0x69, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x73, 0x79, 0x6e, 0x71, 0x2e, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x18,
	0x0a, 0x06, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00,
	0x52, 0x06, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x42, 0x0d, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0x63, 0x0a, 0x0e, 0x57, 0x69, 0x74, 0x68, 0x41,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a,
	0x0e, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65,
	0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x88, 0x01, 0x01, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x61, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x58, 0x0a, 0x0d,
	0x49, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x47, 0x0a,
	0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x73, 0x79, 0x6e, 0x71, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x5b, 0x0a, 0x0e, 0x49, 0x6e, 0x44, 0x61, 0x74, 0x61,
	0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x49, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x73,
	0x79, 0x6e, 0x71, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x22, 0x1e, 0x0a, 0x08, 0x49, 0x6e, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x22, 0x2c, 0x0a, 0x0b, 0x55, 0x6e, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x6a, 0x73, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x71, 0x75, 0x65, 0x72, 0x79, 0x4a, 0x73, 0x6f,
	0x6e, 0x42, 0xa7, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x79, 0x6e, 0x71, 0x2e, 0x71,
	0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x42, 0x0f, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x50, 0x61, 0x72, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x21, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x65, 0x74, 0x73, 0x79, 0x6e, 0x71,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x76, 0x31, 0xa2,
	0x02, 0x03, 0x53, 0x51, 0x58, 0xaa, 0x02, 0x0f, 0x53, 0x79, 0x6e, 0x71, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x69, 0x65, 0x73, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0f, 0x53, 0x79, 0x6e, 0x71, 0x5c, 0x51,
	0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1b, 0x53, 0x79, 0x6e, 0x71,
	0x5c, 0x51, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x53, 0x79, 0x6e, 0x71, 0x3a, 0x3a,
	0x51, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_synq_queries_v1_query_parts_proto_rawDescOnce sync.Once
	file_synq_queries_v1_query_parts_proto_rawDescData []byte
)

func file_synq_queries_v1_query_parts_proto_rawDescGZIP() []byte {
	file_synq_queries_v1_query_parts_proto_rawDescOnce.Do(func() {
		file_synq_queries_v1_query_parts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_synq_queries_v1_query_parts_proto_rawDesc), len(file_synq_queries_v1_query_parts_proto_rawDesc)))
	})
	return file_synq_queries_v1_query_parts_proto_rawDescData
}

var file_synq_queries_v1_query_parts_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_synq_queries_v1_query_parts_proto_goTypes = []any{
	(*IdentifierList)(nil),             // 0: synq.queries.v1.IdentifierList
	(*WithNameSearch)(nil),             // 1: synq.queries.v1.WithNameSearch
	(*WithType)(nil),                   // 2: synq.queries.v1.WithType
	(*WithAnnotation)(nil),             // 3: synq.queries.v1.WithAnnotation
	(*InDataproduct)(nil),              // 4: synq.queries.v1.InDataproduct
	(*InDataPlatform)(nil),             // 5: synq.queries.v1.InDataPlatform
	(*InFolder)(nil),                   // 6: synq.queries.v1.InFolder
	(*Unsupported)(nil),                // 7: synq.queries.v1.Unsupported
	(*WithType_Type)(nil),              // 8: synq.queries.v1.WithType.Type
	(*v1.Identifier)(nil),              // 9: synq.entities.v1.Identifier
	(*v1.DataproductIdentifier)(nil),   // 10: synq.entities.v1.DataproductIdentifier
	(*v11.DataPlatformIdentifier)(nil), // 11: synq.platforms.v1.DataPlatformIdentifier
	(v1.EntityType)(0),                 // 12: synq.entities.v1.EntityType
}
var file_synq_queries_v1_query_parts_proto_depIdxs = []int32{
	9,  // 0: synq.queries.v1.IdentifierList.identifiers:type_name -> synq.entities.v1.Identifier
	8,  // 1: synq.queries.v1.WithType.type:type_name -> synq.queries.v1.WithType.Type
	10, // 2: synq.queries.v1.InDataproduct.identifier:type_name -> synq.entities.v1.DataproductIdentifier
	11, // 3: synq.queries.v1.InDataPlatform.identifier:type_name -> synq.platforms.v1.DataPlatformIdentifier
	12, // 4: synq.queries.v1.WithType.Type.default:type_name -> synq.entities.v1.EntityType
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_synq_queries_v1_query_parts_proto_init() }
func file_synq_queries_v1_query_parts_proto_init() {
	if File_synq_queries_v1_query_parts_proto != nil {
		return
	}
	file_synq_queries_v1_query_parts_proto_msgTypes[3].OneofWrappers = []any{}
	file_synq_queries_v1_query_parts_proto_msgTypes[8].OneofWrappers = []any{
		(*WithType_Type_Default)(nil),
		(*WithType_Type_Custom)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_synq_queries_v1_query_parts_proto_rawDesc), len(file_synq_queries_v1_query_parts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_synq_queries_v1_query_parts_proto_goTypes,
		DependencyIndexes: file_synq_queries_v1_query_parts_proto_depIdxs,
		MessageInfos:      file_synq_queries_v1_query_parts_proto_msgTypes,
	}.Build()
	File_synq_queries_v1_query_parts_proto = out.File
	file_synq_queries_v1_query_parts_proto_goTypes = nil
	file_synq_queries_v1_query_parts_proto_depIdxs = nil
}
