services:
  oracle:
    image: gvenzl/oracle-free:23-slim-faststart
    environment:
      ORACLE_PASSWORD: "SynqTest1"
      APP_USER: "synq_a"
      APP_USER_PASSWORD: "SynqTest1"
    ports:
      - "1521:1521"
    healthcheck:
      test: healthcheck.sh
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s
