package scrappertest

import (
	"context"
	"errors"
	"time"

	"github.com/getsynq/dwhsupport/exec/querycontext"
	"github.com/getsynq/dwhsupport/metrics"
	"github.com/getsynq/dwhsupport/querybuilder"
	"github.com/getsynq/dwhsupport/scrapper"
	. "github.com/getsynq/dwhsupport/sqldialect"
	"github.com/stretchr/testify/suite"
)

// MetricsExecutionConfig provides the table and field information needed to
// generate and execute metric queries against a real database.
type MetricsExecutionConfig struct {
	// TableFqn is the fully qualified table name for the test table.
	TableFqn *TableFqnExpr

	// PartitioningField is a time/date column used for time segmentation (e.g. "created_at").
	PartitioningField string

	// SegmentField is a categorical column used for segmentation (e.g. "category").
	SegmentField string

	// NumericField is a numeric column for profiling (e.g. "price").
	NumericField string

	// TextField is a text column for profiling (e.g. "name").
	TextField string

	// TimeField is a time column for profiling (e.g. "created_at").
	TimeField string
}

// MetricsExecutionSuite validates that SQL generated by the metrics/querybuilder
// packages actually executes successfully against a real database. This catches
// dialect-specific SQL generation bugs that snapshot tests miss.
//
// Embed this in warehouse-specific integration test suites. Set Scrapper and
// Config before tests run (e.g., in SetupSuite).
type MetricsExecutionSuite struct {
	suite.Suite
	Scrapper scrapper.Scrapper
	Config   MetricsExecutionConfig
}

// Ctx returns a background context for use in SetupSuite of embedding suites.
func (s *MetricsExecutionSuite) Ctx() context.Context {
	return context.Background()
}

func (s *MetricsExecutionSuite) ctx() context.Context {
	return querycontext.WithQueryContext(context.Background(), complianceQueryContext)
}

func (s *MetricsExecutionSuite) skipIfNil() {
	if s.Scrapper == nil {
		s.T().Skip("Scrapper not set")
	}
	if s.Config.TableFqn == nil {
		s.T().Skip("TableFqn not configured")
	}
}

func (s *MetricsExecutionSuite) generateAndExecute(qb *querybuilder.QueryBuilder) {
	s.T().Helper()
	dialect := s.Scrapper.SqlDialect()

	sql, err := qb.ToSql(dialect)
	s.Require().NoError(err, "SQL generation should not error")
	s.NotEmpty(sql, "Generated SQL should not be empty")
	s.T().Logf("Generated SQL:\n%s", sql)

	result, err := s.Scrapper.QueryCustomMetrics(s.ctx(), sql)
	if errors.Is(err, scrapper.ErrUnsupported) {
		s.T().Skip("QueryCustomMetrics unsupported")
	}
	s.Require().NoError(err, "Query execution should not error")
	s.NotEmpty(result, "Query should return results")
}

func (s *MetricsExecutionSuite) TestMetricsExecution_VolumeQuery() {
	s.skipIfNil()

	qb := querybuilder.NewQueryBuilder(s.Config.TableFqn, metrics.TableVolumeMetricsCols())
	if s.Config.PartitioningField != "" {
		partitioning := &metrics.MonitorPartitioning{
			Field:    s.Config.PartitioningField,
			Interval: 24 * time.Hour,
		}
		qb = metrics.ApplyMonitorDefArgs(qb, &metrics.MonitorArgs{}, partitioning, 150)
	}

	s.generateAndExecute(qb)
}

func (s *MetricsExecutionSuite) TestMetricsExecution_VolumeWithSegment() {
	s.skipIfNil()
	if s.Config.SegmentField == "" {
		s.T().Skip("SegmentField not configured")
	}

	qb := querybuilder.NewQueryBuilder(s.Config.TableFqn, metrics.TableVolumeMetricsCols())
	args := &metrics.MonitorArgs{
		Segmentation: []*metrics.Segmentation{{
			Expression: Identifier(s.Config.SegmentField),
			Rule:       metrics.AllSegments(),
		}},
	}
	var partitioning *metrics.MonitorPartitioning
	if s.Config.PartitioningField != "" {
		partitioning = &metrics.MonitorPartitioning{
			Field:    s.Config.PartitioningField,
			Interval: 24 * time.Hour,
		}
	}
	qb = metrics.ApplyMonitorDefArgs(qb, args, partitioning, 150)

	s.generateAndExecute(qb)
}

func (s *MetricsExecutionSuite) TestMetricsExecution_SegmentsList() {
	s.skipIfNil()
	if s.Config.SegmentField == "" {
		s.T().Skip("SegmentField not configured")
	}

	args := &metrics.MonitorArgs{
		Segmentation: []*metrics.Segmentation{{
			Expression: Identifier(s.Config.SegmentField),
			Rule:       metrics.AllSegments(),
		}},
	}

	qb, err := metrics.SegmentsListQuery(s.Config.TableFqn, args, nil, 100, 150)
	s.Require().NoError(err)

	dialect := s.Scrapper.SqlDialect()
	sql, err := qb.ToSql(dialect)
	s.Require().NoError(err)
	s.T().Logf("Generated SQL:\n%s", sql)

	segments, err := s.Scrapper.QuerySegments(s.ctx(), sql)
	if errors.Is(err, scrapper.ErrUnsupported) {
		s.T().Skip("QuerySegments unsupported")
	}
	s.Require().NoError(err)
	s.NotEmpty(segments, "SegmentsList should return results")
}

func (s *MetricsExecutionSuite) TestMetricsExecution_NumericFieldStats() {
	s.skipIfNil()
	if s.Config.NumericField == "" {
		s.T().Skip("NumericField not configured")
	}

	dialect := s.Scrapper.SqlDialect()
	cols := metrics.NumericMetricsCols(s.Config.NumericField, dialect)
	qb := querybuilder.NewQueryBuilder(s.Config.TableFqn, cols)

	s.generateAndExecute(qb)
}

func (s *MetricsExecutionSuite) TestMetricsExecution_TextFieldStats() {
	s.skipIfNil()
	if s.Config.TextField == "" {
		s.T().Skip("TextField not configured")
	}

	cols := metrics.TextMetricsCols(s.Config.TextField)
	qb := querybuilder.NewQueryBuilder(s.Config.TableFqn, cols)

	s.generateAndExecute(qb)
}

func (s *MetricsExecutionSuite) TestMetricsExecution_TimeFieldStats() {
	s.skipIfNil()
	if s.Config.TimeField == "" {
		s.T().Skip("TimeField not configured")
	}

	cols := metrics.TimeMetricsCols(s.Config.TimeField)
	qb := querybuilder.NewQueryBuilder(s.Config.TableFqn, cols)

	s.generateAndExecute(qb)
}

func (s *MetricsExecutionSuite) TestMetricsExecution_ProfileColumns() {
	s.skipIfNil()

	var columnsToProfile []*metrics.ColumnToProfile
	if s.Config.NumericField != "" {
		columnsToProfile = append(columnsToProfile, &metrics.ColumnToProfile{
			Column:        s.Config.NumericField,
			ColumnProfile: metrics.ColumnProfileNumeric,
		})
	}
	if s.Config.TextField != "" {
		columnsToProfile = append(columnsToProfile, &metrics.ColumnToProfile{
			Column:        s.Config.TextField,
			ColumnProfile: metrics.ColumnProfileString,
		})
	}
	if s.Config.TimeField != "" {
		columnsToProfile = append(columnsToProfile, &metrics.ColumnToProfile{
			Column:        s.Config.TimeField,
			ColumnProfile: metrics.ColumnProfileTime,
		})
	}
	if len(columnsToProfile) == 0 {
		s.T().Skip("No profile fields configured")
	}
	if s.Config.SegmentField == "" {
		s.T().Skip("SegmentField not configured for profiling")
	}

	dialect := s.Scrapper.SqlDialect()
	args := &metrics.MonitorArgs{
		Segmentation: []*metrics.Segmentation{{
			Expression: Identifier(s.Config.SegmentField),
			Rule:       metrics.AllSegments(),
		}},
	}

	qb, err := metrics.ProfileColumns(dialect, s.Config.TableFqn, columnsToProfile, args, nil, 100, 150)
	s.Require().NoError(err)

	sql, err := qb.ToSql(dialect)
	s.Require().NoError(err)
	s.T().Logf("Generated SQL:\n%s", sql)

	result, err := s.Scrapper.QueryCustomMetrics(s.ctx(), sql)
	if errors.Is(err, scrapper.ErrUnsupported) {
		s.T().Skip("QueryCustomMetrics unsupported")
	}
	s.Require().NoError(err)
	s.NotEmpty(result, "ProfileColumns query should return results")
}
