SELECT user_id,
       query_id,
       query_label,
       transaction_id,
       session_id,
       database_name,
       query_type,
       status,
       result_cache_hit,
       start_time,
       end_time,
       elapsed_time,
       queue_time,
       execution_time,
       error_message,
       returned_rows,
       returned_bytes,
       query_text,
       redshift_version,
       usage_limit,
       compute_type,
       compile_time,
       planning_time,
       lock_wait_time,
       service_class_id,
       service_class_name,
       query_priority,
       short_query_accelerated,
       generic_query_hash,
       user_query_hash
FROM SYS_QUERY_HISTORY
WHERE end_time BETWEEN $1 AND $2
