name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Run go generate
        run: go generate ./...
      - name: Check generated code is up to date
        run: |
          if [ -n "$(git diff --name-only)" ]; then
            echo "Generated code is out of date. Please run 'go generate ./...' and commit the changes."
            git diff
            exit 1
          fi
      - name: Test
        run: go test -v ./...
