defaults:
  run:
    shell: bash
env:
  GONOPROXY: github.com/getsynq/*
  GONOSUMDB: github.com/getsynq/*
  GOPRIVATE: github.com/getsynq/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v3
      with:
        go-version: 1.22
        go-version-file: 'go.mod'
    - name: Configure git
      run: git config --global --add url."git@github.com:".insteadOf "https://github.com/"
    - name: Build
      run: |
        go get
        go generate
        GOOS=darwin CGO_ENABLED=0 GOARCH=amd64 go build -o synq-dwh-amd64-darwin main.go
        GOOS=darwin CGO_ENABLED=0 GOARCH=arm64 go build -o synq-dwh-arm64-darwin main.go
        GOOS=linux CGO_ENABLED=0 GOARCH=amd64 go build -o synq-dwh-amd64-linux main.go
        GOOS=linux CGO_ENABLED=0 GOARCH=arm64 go build -o synq-dwh-arm64-linux main.go
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
         synq-dwh-amd64-darwin
         synq-dwh-arm64-darwin
         synq-dwh-amd64-linux
         synq-dwh-arm64-linux
name: release synq-dwh
"on":
  push:
    tags:
      - v*.*.*
